# Generated by Django 6.0.4 on 2026-04-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
